services:
  db:
    image: postgres:13
    container_name: postgresql
    environment:
      POSTGRES_DB: Tamliani
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: ./app
    container_name: python_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/Tamliani
